on:
  push:
  pull_request:

name: check

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: install boost
        run: sudo apt install libboost-all-dev

      - name: build
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: run example 1
        run: |
          cd build 
          ./ex_gridworld_online 
          cd ..

      #- name: run example 2
      #  run: |
      #    cd build 
      #    ./ex_gridworld_offline
      #    cd ..

      #- name: run example 3: requires user input to stop
      #  run: |
      #    cd build 
      #    ./ex_blackjack
      #    cd ..
