on:
  push:
  pull_request:

name: check

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: install boost
        run: sudo apt install libboost-all-dev

      - name: build
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: run example 1
        run: ./ex_gridworld_online

      - name: run example 2
        run: ./ex_gridworld_offline

      - name: run example 3
        run: ./ex_blackjack
